version: "3.5"
services:
  aztec:
    build:
      context: .
      args:
        UPSTREAM_VERSION: 0.87.2
    volumes:
      - data:/root
    environment:
      - COINBASE=
      - VALIDATOR_PRIVATE_KEY=
      - ETHEREUM_HOSTS=http://geth.sepolia-geth.dappnode:8545
      - L1_CONSENSUS_HOST_URLS=http://prysm-sepolia.dappnode:3500
      - BLOB_SINK_URL=
      - SEQ_MIN_TX_BLOCK=
      - SEQ_MAX_TX_BLOCK=
    ports:
      - 40400:40400
      - 40400:40400/udp
    restart: unless-stopped
volumes:
  data: {}
