version: "3.5"
services:
  sequencer:
    build:
      context: ./sequencer
      args:
        UPSTREAM_VERSION: 0.87.2
    volumes:
      - data:/root
    environment:
      - COINBASE=
      - VALIDATOR_PRIVATE_KEY=
      - ETHEREUM_HOSTS=http://geth.sepolia-geth.dappnode:8545
      - L1_CONSENSUS_HOST_URLS=http://prysm-sepolia.dappnode:3500
      - BLOB_SINK_URL=
      - SEQ_MIN_TX_BLOCK=
      - SEQ_MAX_TX_BLOCK=
    ports:
      - 40400:40400/tcp
      - 40400:40400/udp
    restart: unless-stopped
  register:
    build:
      context: ./register
      args:
        UPSTREAM_VERSION: 0.87.2
    environment:
      - ETHEREUM_HOSTS=${ETHEREUM_HOSTS:-http://geth.sepolia-geth.dappnode:8545}
      - VALIDATOR_PRIVATE_KEY=
      - COINBASE=
    restart: "no"
volumes:
  data: {}
